ingresses:
  - https://kaptein.intern.dev.nav.no
  - https://kaptein.ansatt.dev.nav.no
tenant: trygdeetaten.no
roles:
  - 7ad08bfe-68d4-4c84-bddd-82d8894fb36e # KABAL_OPPGAVESTYRING_ALLE_ENHETER
  - 07add1e7-7195-4c37-828d-fdf23ec6bef1 # KABAL_SAKSBEHANDLING
  - 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7 # KABAL_INNSYN_EGEN_ENHET
  - 14d756b4-d014-419a-a5bc-b8f9e31ce248 # KABAL_ADMIN


