name: Sanity Build

on: [pull_request]

jobs:
  sanity-build:
    strategy:
      fail-fast: false
      matrix:
        apps: [frontend, server]
    name: ${{ matrix.apps }} Sanity Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - name: Install common dependencies
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          echo -e "\n[install.scopes]\n\"@navikt\" = { token = \"$BUN_AUTH_TOKEN\", url = \"https://npm.pkg.github.com/\" }" >> bunfig.toml
          bun install --frozen-lockfile

      - name: Install ${{ matrix.apps }} dependencies
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          cd ${{ matrix.apps }}
          echo -e "\n[install.scopes]\n\"@navikt\" = { token = \"$BUN_AUTH_TOKEN\", url = \"https://npm.pkg.github.com/\" }" >> bunfig.toml
          bun install --frozen-lockfile

      - name: Restore cache for ${{ matrix.apps }}
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{matrix.apps}}/.tsbuildinfo
          key: ${{ matrix.apps }}-${{ github.ref_name }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }} # This will never hit, but it is required.
          restore-keys: |
            ${{ matrix.apps }}-${{ github.ref_name }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}
            ${{ matrix.apps }}-shared-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}

      - name: Typecheck ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun run typecheck

      - name: Lint ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          npm run lint

      - name: Test ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun test

      - name: Save cache for ${{ matrix.apps }}
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            ${{matrix.apps}}/.tsbuildinfo
          key: ${{ matrix.apps }}-${{ github.ref_name }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}-${{ github.run_id }}
